### ISSUE TITLE
Index error in genotyping stage

### ISSUE THREAD

**Issue by Varunachander** [baezortega/somatypus#2] opened 2019-09-06 19:22 UTC
Hi, 
I encountered an issue using Somatypus in the genotyping stage.

(8) PREPARING DATA FOR VARIANT GENOTYPING
Traceback (most recent call last):
  File "/hgsccl/next-gen/scratch/chander/software/somatypus/src/Somatypus_ExtractRegions.py", line 138, in <module>
   
start = int(exonComp[1].split('-')[0])
IndexError: list index out of range

ERROR: Output file /hgsccl/next-gen/scratch/chander/somatypus_out/8-18_genotyped/was not correctly generated. Please check the logs folder for more information.

Any thoughts why this error occurs?

Best,
Varuna

**Comment by baezortega** [comment] 2019-09-09 18:00
Hi Varuna,

Thanks for using Somatypus!

It seems that there was a problem while parsing your file of genomic regions – a guess you are using a set of regions for calling? Can you check that all the lines of the file have a structure like:

CHROM:START-END

For example: **chr1:12000-13500**

If there is nothing wrong with the regions, could you also check that there isn't a blank line at the end of the file?

Best,
Adrian

**Comment by Varunachander** [comment] 2019-09-10 03:29
Hi Adrian, 
Thanks for the quick response. My bed file starts as:
1       2985792 2985892

I tried changing bed file to have this format below:
1:2985792-2985892

This time, It crashes right at the beginning during variant calling.

**Error:**
Calling on SI10000432_H2KKCBCX3-2-IDMB71.realigned.recal.bam

2019-09-09 22:09:04,505 - INFO - Beginning variant calling
2019-09-09 22:09:04,505 - INFO - Output will go to /hgsccl/next-gen/scratch/chander/somatypus_out/newbed/1-2_individual_calls/platypusVariants_SI10000432_H2KKCBCX3-2-IDMB71.realigned.recal_default.vcf
2019-09-09 22:09:04,612 - INFO - Interpreting --regions argument (new_HG19_Cardio_RiskPGxLD.bed) as a BED file with regions in the format chr	start	end
/hgsccl/next-gen/scratch/chander/software/somatypus/src/somatypus: line 91: 26401 Segmentation fault      Platypus.py callVariants --logFileName=$OUTDIR/logs/1_individual_default/"${NAME%.*}"_default.log --refFile=$REFERENCE --bamFiles=$FILE $REGIONSARG --minPosterior=0 --minReads=3 --nCPU=$CPUS $EXTRA -o $OUTDIR/1-2_individual_calls/platypusVariants_"${NAME%.*}"_default.vcf

ERROR: Output file /hgsccl/next-gen/scratch/chander/somatypus_out/newbed/1-2_individual_calls/platypusVariants_SI10000327_H2KKCBCX3-2-IDMB1.realigned.recal_default.vcf was not correctly generated. Please check the logs folder for more information.

**Comment by baezortega** [comment] 2019-09-10 07:33
Hi Varuna,

I think I know what the problem is. The caller is expecting a BED format
because your file has .bed extension. Could you change the extension to
.txt? Then it should be able to use it.

Best,
Adrian

**Comment by Varunachander** [comment] 2019-09-10 15:45
Hi Adrian, 

Thanks. Should I change it  to .txt for just the final genotyping step or even for first step which is variant calling?

Best,
Varuna

**Comment by baezortega** [comment] 2019-09-10 15:48
Hi Varuna,

If the initial variant calling went OK there's no need to repeat it, but if
you plan to run the entire pipeline again I would change it from the start.

Adrian

**Comment by Varunachander** [comment] 2019-09-10 16:56
Hi Adrian,

I converted my bed file to a .txt file and trying to run the genotyping step alone since variant calling went fine with no issues (steps 1-7).

I am getting errors when I run this in command line:

./Somatypus_ExtractRegions.py /hgsccl/next gen/scratch/chander/new_HG19_Cardio_RiskPGxLD.txt  /hgsccl/next-gen/scratch/chander/somatypus_out/5-7_merged/MergedSNVs_allele1.vcf /hgsccl/next-gen/scratch/chander/somatypus_out/5-7_merged/MergedSNVs_allele2.vcf  /hgsccl/next-gen/scratch/chander/somatypus_out/5-7_merged/MergedSNVs_allele3.vcf </hgsccl/next-gen/scratch/chander/somatypus_out/5-7_merged/MergedIndels.vcf | "none" > /hgsccl/next-gen/scratch/chander/somatypus_out/8-18_genotyped/genotyping 0/1

errors:
close failed in file object destructor:
sys.excepthook is missing
lost sys.stderr

**Comment by baezortega** [comment] 2019-09-10 17:23
Hi Varuna,

I think running the Somatypus_ExtractRegions.py script separately might be very tricky. I think you should re-run Somatypus using the project directory you already have; if you indicate the same output directory as for steps 1-7, then the pipeline should resume on step 8 automatically. Otherwise you can tell the pipeline where to start by changing the contents of the CHECKPOINT file in the project directory (now it should contain the names of steps 1 to 7 – or 1 to 6, if the extraction of regions for genotyping didn't work).

Best,
Adrian

**Comment by Varunachander** [comment] 2019-09-10 19:04
Hi Adrian,

Yes I did what you said and it went straight to genotyping. It was going fine until it gave me this error and stopped.

2019-09-10 13:59:40,475 - INFO - Processing region 2:21227950-21235523. (Only printing this message every 10 regions of size 100000)
2019-09-10 14:00:10,407 - WARNING - Too many reads (5000000) in region 2:21227950-21235523. Quitting now. Either reduce --bufferSize or increase --maxReads.
2019-09-10 14:00:11,564 - INFO - Skipping region 2:21227950-21235523 as data could not be loaded

**Comment by Varunachander** [comment] 2019-09-11 18:38
Hi Adrian,

The genotyping finished for all, except two regions. The example for one region is specified in my message above. 

I am trying to open VCF Files under folder 5-7_merged  using bcftools and I am unable to open them. I am able to open vcf files in other folders, except the ones in this folder. (5-7_merged).
Error example:

Failed to open MergedIndels.vcf: unknown file type
(END) 

Any idea why?

Really appreciate your timely help 
-Varuna

**Comment by baezortega** [comment] 2019-09-12 07:09
Hi Varuna,

The two regions that failed genotyping have more than 5 million reads
mapped to them, so the caller skipped them. Normally I won't advise you to
trust variants in regions with so many reads, but if you need to, you can
change the bufferSize option using the -p command line option in Somatypus
(see the usage instructions; it should be something like -p
"--bufferSize=500"). This will divide the regions into smaller regions (500
bp in the example above).

I think the reason why the merged VCFs are not recognised is that they
don't have a header, but you can open them with a text editor (e.g. nano).

Best,
Adrian

**Comment by Varunachander** [comment] 2019-09-14 00:10
Great, thanks Adrian!

**Closed as completed** 2019-09-14 00:10 UTC
